import { z } from 'zod';
import { getInvoicePaymentFromDatabase, resubmitInvoicePaymentInDatabase } from '@/data/payment-requests/invoice-payment/prisma-repository';
import { dataResponse } from '@/lib/api/response';
export const dynamic = 'force-dynamic';
type Context = { params: Promise<{ id: string }> };
export async function GET(_request: Request, context: Context) { try { const { id } = await context.params; const record = await getInvoicePaymentFromDatabase(decodeURIComponent(id)); return record ? dataResponse(record) : Response.json({ error: 'NOT_FOUND', message: 'Invoice Payment could not be found.' }, { status: 404 }); } catch (error) { return Response.json({ error: 'DATABASE_ERROR', message: error instanceof Error ? error.message : 'Invoice Payment could not be loaded.' }, { status: 500 }); } }
const documentSchema = z.object({ id: z.string().min(1), fileName: z.string().min(1), mimeType: z.string(), size: z.number().int().nonnegative(), dataUrl: z.string().min(1) });
const resubmitSchema = z.object({ organizationId: z.string().min(1), requestDate: z.string().min(1), staffId: z.string().min(1), staffName: z.string().trim().min(1), projectName: z.string().trim().min(1), title: z.string().trim().min(1), purpose: z.string().trim().min(1), vendorName: z.string().trim().min(1), eInvoiceLink: z.string().url(), transferType: z.enum(['GIRO', 'INSTANT']), paymentPortion: z.enum(['UPFRONT_50', 'BALANCE_50', 'FULL', 'OTHER']), paymentPortionOther: z.string().optional(), managerApproverId: z.string().min(1), directorApproverId: z.string().min(1), currency: z.literal('MYR'), invoiceTotal: z.number().positive(), taxAmount: z.number().nonnegative(), requestedAmount: z.number().positive(), supportingDocuments: z.array(documentSchema).min(1).max(5), remarks: z.string().optional() });
export async function PATCH(request: Request, context: Context) { const parsed = resubmitSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return Response.json({ error: 'INVALID_INVOICE_PAYMENT', message: 'Complete all required Invoice Payment fields.', details: parsed.error.flatten() }, { status: 400 }); try { const { id } = await context.params; return dataResponse(await resubmitInvoicePaymentInDatabase(decodeURIComponent(id), parsed.data)); } catch (error) { return Response.json({ error: 'DATABASE_ERROR', message: error instanceof Error ? error.message : 'Invoice Payment could not be resubmitted.' }, { status: 500 }); } }
