'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { fetchClaimRequest, processClaimByFinance, returnClaimByFinance } from '@/data/payment-requests/claims/api';
import { notifyClaimPaid, notifyClaimReturned } from '@/features/payment-request/notifications/claim-notifications';
import type { ClaimRecord } from '@/domain/payment-requests/claims/types';
import { readBetaSession, type BetaAccount } from '@/lib/auth/beta-accounts';
import { ClaimReviewDetails, ClaimWorkflow } from '../claim-review-shared';
import styles from '../claim-workflow.module.css';

const today = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60_000).toISOString().slice(0, 10);

export function ClaimFinanceReview({ requestId }: { requestId: string }) {
  const [account, setAccount] = useState<BetaAccount | null>(null); const [record, setRecord] = useState<ClaimRecord | null>(null); const [checked, setChecked] = useState(false); const [paymentDate, setPaymentDate] = useState(today()); const [reference, setReference] = useState(''); const [notes, setNotes] = useState(''); const [remarks, setRemarks] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { setAccount(readBetaSession()); fetchClaimRequest(requestId).then(setRecord).catch((caught) => setError(caught instanceof Error ? caught.message : 'The Claim could not be loaded.')).finally(() => setChecked(true)); }, [requestId]);
  async function processPayment() { if (!account || !record) return; if (!paymentDate || !reference.trim()) return setError('Enter the payment date and reference.'); setSaving(true); setError(''); setSuccess(''); try { const updated = await processClaimByFinance(record.id, account.id, { paymentDate, paymentReference: reference.trim(), notes: notes.trim() || undefined }); notifyClaimPaid(updated, account); setRecord(updated); setSuccess('Finance processing completed. The Claim is now marked Paid.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'The Claim could not be processed.'); } finally { setSaving(false); } }
  async function returnRequest() { if (!account || !record) return; if (remarks.trim().length < 3) return setError('Enter correction remarks before returning the Claim.'); setSaving(true); setError(''); try { const updated = await returnClaimByFinance(record.id, account.id, remarks.trim()); notifyClaimReturned(updated, account, 'Finance'); setRecord(updated); } catch (caught) { setError(caught instanceof Error ? caught.message : 'The Claim could not be returned.'); } finally { setSaving(false); } }
  if (!checked) return <State title="Loading Claim" copy="Reading the Claim and receipts…" />;
  if (!account || account.role !== 'finance') return <State title="Finance access required" copy="This page is available only to Finance." />;
  if (!record) return <State title="Claim not found" copy={error || 'This Claim could not be found.'} />;
  const actionable = ['PENDING_MANAGER_APPROVAL', 'PENDING_DIRECTOR_APPROVAL', 'PENDING_FINANCE_PROCESSING'].includes(record.status);
  return <main className={styles.page}><div className={styles.back}><Link href="/beta/finance/payment-requests/claims">← Back to Claims</Link></div>{error && <div className={styles.error} role="alert">{error}</div>}{success && <div className={styles.success} role="status">{success}</div>}<div className={styles.detailLayout}><section className={styles.detailMain}><ClaimReviewDetails contextLabel="Finance processing" record={record} userId={account.id} /></section><aside className={styles.rail}><section className={styles.actionCard}><p>Finance action</p><h2>{actionable ? 'Verify payment' : record.status === 'PAID' ? 'Payment completed' : 'No Finance action'}</h2>{actionable ? <><span>Verify the Claim form and receipts, record payment details, then complete the Claim.</span><div className={styles.financeFields}><label><span>Payment date *</span><input onChange={(event) => setPaymentDate(event.target.value)} type="date" value={paymentDate} /></label><label><span>Payment reference *</span><input onChange={(event) => setReference(event.target.value)} placeholder="Bank reference or transaction ID" value={reference} /></label><label><span>Finance remarks</span><textarea onChange={(event) => setNotes(event.target.value)} placeholder="Optional processing notes" rows={3} value={notes} /></label></div><button className={styles.primary} disabled={saving || !paymentDate || !reference.trim()} onClick={processPayment} type="button">Verify and mark completed →</button><div className={styles.divider}>or return with notes</div><label><span>Reason for returning</span><textarea onChange={(event) => setRemarks(event.target.value)} placeholder="Explain what the claimant must correct" rows={4} value={remarks} /></label><button className={styles.returnButton} disabled={saving || remarks.trim().length < 3} onClick={returnRequest} type="button">Return to claimant</button></> : <><span>This Claim is currently {record.status.replaceAll('_', ' ').toLowerCase()}.</span>{record.returnRemarks && <p className={styles.remark}><strong>Finance remark:</strong> {record.returnRemarks}</p>}</>}</section><ClaimWorkflow record={record} /></aside></div></main>;
}
function State({ title, copy }: { title: string; copy: string }) { return <main className={styles.state}><h1>{title}</h1><p>{copy}</p><Link href="/beta/finance/payment-requests/claims">Back to Finance Claims</Link></main>; }
