'use client';
import { useEffect, useRef, useState } from 'react';
import { useUserSignature } from '../hooks/use-user-signature';
import { PaymentPageState } from '@/shared/payment-page-state';
import styles from './director-signature.module.css';

export function SignatureUpload({ userId, userName, roleLabel }: { userId: string; userName: string; roleLabel: string }) {
    const inputRef = useRef<HTMLInputElement>(null);
    const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState(''); const [localError, setLocalError] = useState(''); const [message, setMessage] = useState('');
    const { signature, isLoading, isSaving, error, uploadSignature, removeSignature } = useUserSignature(userId);
    useEffect(() => { if (!file) return setPreview(''); const url = URL.createObjectURL(file); setPreview(url); return () => URL.revokeObjectURL(url); }, [file]);
    async function save() { if (!file) return setLocalError('Please select a signature image.'); setLocalError(''); setMessage(''); try { await uploadSignature(file); setFile(null); if (inputRef.current) inputRef.current.value = ''; setMessage('Your signature was saved successfully in PostgreSQL.'); } catch { } }
    if (isLoading) return <PaymentPageState title="Loading Signature Settings" copy="Reading your active signature…" backHref="/beta" backLabel="Back to Dashboard" />;
    return <section className={styles.signaturePanel}><header className={styles.signatureHeader}><div><p>{roleLabel} signature</p><h1>My Signature</h1><span>This signature belongs to {userName} and will be used for authorized workflow actions.</span></div><span className={signature ? styles.signatureAvailable : styles.signatureMissing}>{signature ? 'Signature available' : 'Signature required'}</span></header>
        {(localError || error) && <div className={styles.signatureError}>{localError || error}</div>}{message && <div className={styles.signatureSuccess}>{message}</div>}
        <div className={styles.signatureLayout}><div className={styles.signaturePreview}><span>Signature preview</span><div className={styles.signatureCanvas}>{preview || signature?.imageUrl ? <img alt={`${userName} signature`} src={preview || signature?.imageUrl} /> : <div className={styles.signaturePlaceholder}><strong>No signature uploaded</strong><p>A transparent PNG provides the cleanest result.</p></div>}</div>{signature && !file && <dl className={styles.signatureMetadata}><div><dt>File</dt><dd>{signature.fileName}</dd></div><div><dt>Size</dt><dd>{Math.ceil(signature.fileSize / 1024)} KB</dd></div><div><dt>Uploaded</dt><dd>{new Date(signature.createdAt).toLocaleString('en-MY')}</dd></div></dl>}</div>
            <div className={styles.signatureControls}><div><h2>{signature ? 'Replace signature' : 'Upload signature'}</h2><p>Upload PNG, JPG or WebP. Maximum size is 300 KB.</p></div><label className={styles.signatureFileField}><span>Select signature image</span><input ref={inputRef} accept="image/png,image/jpeg,image/webp" onChange={(event) => { setFile(event.target.files?.[0] ?? null); setMessage(''); setLocalError(''); }} type="file" /></label>{file && <div className={styles.selectedFile}><div><strong>{file.name}</strong><span>{Math.ceil(file.size / 1024)} KB</span></div></div>}<button className={styles.saveSignatureButton} disabled={!file || isSaving} onClick={save} type="button">{isSaving ? 'Saving signature…' : signature ? 'Save replacement' : 'Save signature'}</button>{signature && <button className={styles.removeSignatureButton} disabled={isSaving} onClick={async () => { if (window.confirm('Remove your active signature? Historical approvals will retain their signature reference.')) { await removeSignature(); setMessage('The active signature was removed.'); } }} type="button">Remove active signature</button>}<aside className={styles.signatureNotice}><strong>Database-backed beta storage</strong><p>PostgreSQL stores the active signature reference and file metadata. The private image file stays outside the public folder.</p></aside></div>
        </div></section>;
}
